### ISSUE TITLE
[SUGGESTION] Age and Role Fields

### ISSUE THREAD

**Issue by VexTheWanderer01** [The-ProxyFox-Group/ProxyFox#6]
**Describe your feature**
I think that the descriptions on the sheets should be cleaner, with more space for other things.

**Describe the solution you'd like**
I think that adding an age and role field just like the pronouns and birthday would be great, and adding a command similar to the switch command for age sliders. The age command would "switch" the age field.

**Describe alternatives you've considered**
Using the description, which would take up more of the precious 1k character space.

**Additional context**
It might (???) be difficult to add due to pluralkit imports.

**Comment by Oliver-makes-code** [comment]
This has to do with database changes, so I'm assigning @KJP12
